### ISSUE TITLE
path.split error

### ISSUE THREAD

**Issue by ryanrotman** [myogeshchavan97/multi-step-form-using-mern#1]
Hello. I'm working through your project on freeCodeCamp. I'm early on and just added the code for the section "How to Create the First Step Form" and after adding that code I've received an error on a path.split is not a function. I'm struggling to find where that error is actually coming from. Any help would be greatly appreciated. Here is the link to my repo. Everything is current to that step in the project. [https://github.com/ryanrotman/mern-reg-form](https://github.com/ryanrotman/mern-reg-form)
<img width="1552" alt="error_path_split" src="https://user-images.githubusercontent.com/67814115/115652846-a5f54780-a2f3-11eb-98e9-745f341cd175.png">

**Comment by myogeshchavan97** [comment]
Hi @ryanrotman, `react-hook-form` library has breaking changes starting from version `7.0.0`. As you're using `react-hook-form` with version `7.2.2`, you're getting this error. Please use the same version as I have given in the article.

As you're using npm instead of yarn, execute the following command 

```
npm install axios@0.21.1 bootstrap@4.6.0 react-bootstrap@1.5.0 country-state-city@2.0.0 framer-motion@3.7.0 node-sass@4.14.1 react-hook-form@6.15.4 react-router-dom@5.2.0 sweetalert2@10.15.5
```

in the terminal from your project folder and you will not have any issue following the article.

**Comment by myogeshchavan97** [comment]
@ryanrotman  Let me know If you face any further issue while following the article. Happy to help you

**Comment by ryanrotman** [comment]
@myogeshchavan97 Thank you so much for the help. I really appreciate it.
